CREATE TABLE `roadmaps` (
	`id` int AUTO_INCREMENT NOT NULL,
	`firstName` varchar(255) NOT NULL,
	`businessName` varchar(255) NOT NULL,
	`businessType` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`monthlyRevenue` varchar(100),
	`mainOffer` text,
	`crmUsage` varchar(255),
	`leadResponseSpeed` varchar(255),
	`missedLeads` varchar(100),
	`chatAgents` varchar(255),
	`contentFrequency` varchar(100),
	`audienceSize` varchar(100),
	`instagramHandle` varchar(255),
	`monthlyAdBudget` varchar(100),
	`ninetyDayGoal` text,
	`biggestFrustration` text,
	`phone` varchar(50),
	`website` varchar(500),
	`titanRoadmap` text NOT NULL,
	`offerPlaybook` text,
	`facebookAdLaunch` text,
	`instagramGrowth` text,
	`leadGeneration` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `roadmaps_id` PRIMARY KEY(`id`)
);
